# Generated by Django 5.0.6 on 2024-07-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do',
            options={'verbose_name': 'To Do', 'verbose_name_plural': 'To Dos'},
        ),
    ]
